Применение ООП-стиля в поисковике
nastybits/go-core pull request #12
Opened 2020-11-23 12:15 UTC by nastybits

Изменений не очень много. Привел к виду похожему на gosearch в репозитории курса. Пока не отказался от файлового кэша и функций Load и Save в пакете движка, т.к. они пока достаточно удобны.

2020-11-25 15:15 UTC, DmitriyVTitov requested changes
**Предлагается создать отдельный исполняемый пакет, в котором была бы разработана структура данных и методы для приложения-сервера.** 

У тебя же всё в пакете `cmd`, а такого вообще существовать не должно. Дальше не смотрел, это важно.

2020-11-30 14:03 UTC, DmitriyVTitov approved these changes
Принято!

2020-11-30 14:03 UTC, DmitriyVTitov commented on lesson7/cmd/gosearch/main.go
> +			fmt.Println("Не удалось просканировать сайты")
сюда лучше добавить текст ошибки (`err.Error()`), иначе причина не ясна

2020-11-30 14:03 UTC, DmitriyVTitov commented on lesson7/pkg/cache/local/local.go
> +package local
вообще говоря, это не кэш, а хранилище данных.
т.е. замена БД

2020-12-06 09:31 UTC, mrosminin commented on lesson7/pkg/index/index.go
> +// inArray - поиск элемента в срезе. Возвращает его индекс или -1 если элемент не найден
true/false

2021-06-02 15:08 UTC, merged