Передача поискового робота в поисковый движок с использованием интерфейса
nastybits/go-core pull request #4
Opened 2020-10-29 16:28 UTC by nastybits

По техническим причинам опоздал. Но буду нагонять.

Вроде сделал все по ТЗ, но есть сомнения на счет именования структур и методов. Знаю, что мы ушли далеко вперед, но посмотри плиз. Специально пропускал части с разборами домашних заданий в лекциях.

2020-10-31 11:28 UTC, DmitriyVTitov requested changes
Этот код не должен запускаться (в части тестов).

2020-10-31 11:28 UTC, DmitriyVTitov commented on lesson3/engine/cmd/engine/go.mod
> +module education/lesson3/engine/cmd/engine
почему-то вспомнилось `We don't need no education!`

2020-10-31 11:28 UTC, DmitriyVTitov commented on lesson3/engine/cmd/engine/main.go
> +}
две одинаковых функции по сути

2020-10-31 11:28 UTC, DmitriyVTitov commented on lesson3/engine/cmd/engine/main.go
> +	}
хотя бы вот это можно было засунуть в функцию `scan`

2020-10-31 11:28 UTC, DmitriyVTitov commented on lesson3/engine/cmd/engine/main_test.go
> +	}
OK, так нормально, вижу смысл в интерфейсе.
большинство сделали функцию `scan` из одной строчки как у тебя и максимум тестировали её же. а обычно заглушка оставалась неиспользованной.

2020-10-31 11:28 UTC, DmitriyVTitov commented on lesson3/engine/cmd/engine/main_test.go
> +	data, err := scan(&s, "stub", 2)
логичнее тогда `s := new(stub.StubScanner)`

2020-10-31 11:28 UTC, DmitriyVTitov commented on lesson3/engine/cmd/engine/main_test.go
> +	var s stub.StubScanner
стоп, но там нет типа `stub.StubScanner`!
это чего ещё за фигня?

2020-10-31 11:28 UTC, DmitriyVTitov commented on lesson3/engine/cmd/engine/main_test.go
> +	data, err := scan(&s, "stub", 2)
да и функция принимает не указатель, а значение!

2020-11-01 20:43 UTC, nastybits commented on lesson3/engine/cmd/engine/main_test.go
> +	var s stub.StubScanner
Это видимо я накосячил с передлками и забыл поменять в тесте. Торопился очень

2020-11-04 15:35 UTC, nastybits commented
@DmitriyVTitov в общем, разобрался с go.mod спасибо за помощь. Исправил ДЗ и почти закончил следующее. Здесь много изменений  во всех каталогах из-за переименования папки проекта, но в ДЗ  №3 изменения только по твоим замечаниям в каталоге lesson3.

2020-11-07 15:12 UTC, DmitriyVTitov approved these changes
Решено, но:
1. бардак!
2. уже забыл, смотри рецензию.

2020-11-07 15:12 UTC, DmitriyVTitov commented on lesson1/cmd/lesson1/main.go
> +	"go.core/lesson1/pkg/fibonacci"
вот это-то здесь какого хрена опять делает?
почему тут `lesson1`?

2020-11-07 15:12 UTC, DmitriyVTitov commented on lesson3/engine/cmd/engine/main.go
> +}
ох, ё-моё!
мог бы добавить в пакет сканера тип данных и переделать функцию на метод.
эти все вещи никакого отношения к исполняемому пакету не имеют.

2020-11-07 15:12 UTC, DmitriyVTitov commented on lesson3/engine/cmd/engine/main.go
> +}
да и функция ни о чём, никакой привнесённой логики

2020-11-07 15:12 UTC, DmitriyVTitov commented on lesson3/engine/cmd/engine/main_test.go
> +	}
ОК, но это уже сложновато, конечно.
но ОК

2020-11-07 15:12 UTC, DmitriyVTitov commented on lesson3/engine/cmd/engine/main_test.go
> +		{"6", "some", 9},
всегда нужно указывать имена полей, возьми за привычку

2020-11-07 15:12 UTC, DmitriyVTitov commented on lesson3/engine/pkg/stub/stub.go
> +func (s Spider) Scan(url string, depth int) (map[string]string, error) {
вот здесь-то добавил тип и метод.
что мешало то же самое сделать и с пакетом основного сканера?

2020-11-07 15:13 UTC, DmitriyVTitov commented on lesson3/engine/cmd/engine/main_test.go
> +	}
в смысле, что функция, принимающая интерфейс тут вспомогательная
я ожидал теста самой функции с интерфейсом, но смысл понят верно

2020-11-09 07:53 UTC, merged