Разработка быстрого индекса
nastybits/go-core pull request #6
Opened 2020-11-05 13:00 UTC by nastybits

Closes #5

2020-11-06 13:58 UTC, DmitriyVTitov requested changes
Каждое ДЗ должно быть в отдельном каталоге. Решение должно быть ссылкой на полностью зелёный PR, без лишних файлов.
Это невозможно проверять! 34 файла!

![image](https://user-images.githubusercontent.com/38575605/98374144-4d860280-2051-11eb-8442-1d1169d0494f.png)

2020-11-06 13:58 UTC, DmitriyVTitov commented
Фибоначчи какой-то тут! Что за хрень?

2020-11-06 14:33 UTC, nastybits commented
@DmitriyVTitov Ты хоть читаешь описание PR?

> Лучше сначала посмотреть #4 когда его приму тут останутся только файлы для 4-го урока.

Я изменил название рабочего каталога. Поэтому 34 файла, везде где был go.mod поменялись линки.

2020-11-06 14:36 UTC, DmitriyVTitov commented
> @DmitriyVTitov Ты хоть читаешь описание PR?
> 
> > Лучше сначала посмотреть #4 когда его приму тут останутся только файлы для 4-го урока.
> 
> Я изменил название рабочего каталога. Поэтому 34 файла, везде где был go.mod поменялись линки.

А чего читать-то? Каждое ДЗ в отдельном каталоге в отдельной ветке. Ты видел картинку? Ну как это проверять?

2020-11-10 23:35 UTC, DmitriyVTitov approved these changes
Слишком сложно.

2020-11-10 23:35 UTC, DmitriyVTitov commented on lesson4/engine/cmd/engine/main.go
> +	// fmt.Printf("%v", storage)
небрежность

2020-11-10 23:35 UTC, DmitriyVTitov commented on lesson4/engine/cmd/engine/main.go
> +	var text string
лучше `s string` или `query string` но не `text`

2020-11-10 23:35 UTC, DmitriyVTitov commented on lesson4/engine/pkg/document/document.go
> +}
может на ПэХаПэ это и нормально, но тут выглядит ужасно.
не надо для каждой модели создавать пакет.

2020-11-10 23:35 UTC, DmitriyVTitov commented on lesson4/engine/pkg/document/document.go
> +}
не заслуживает документ такого

2020-11-10 23:35 UTC, DmitriyVTitov commented on lesson4/engine/pkg/document/document.go
> +}
да и вообще не очень принято для всех полей делать геттеры.

2020-11-10 23:35 UTC, DmitriyVTitov commented on lesson4/engine/pkg/document/document.go
> +}
вот это выглядит уже разумней, но всё равно, считаю, что этот пакет - излишнее усложнение

2020-11-10 23:35 UTC, DmitriyVTitov commented on lesson4/engine/pkg/index/index.go
> +type Storage map[string][]int
почему в пакете Индекс первым делом экспортируется тип Сторадж?

2020-11-10 23:35 UTC, DmitriyVTitov commented on lesson4/engine/pkg/index/index.go
> +}
и конструктор создаёт не индекс - не логично

2020-11-10 23:35 UTC, DmitriyVTitov commented on lesson4/engine/cmd/engine/main.go
> +func find(IDs []int, d []document.Documenter) (res []document.Documenter) {
возвращать интерфейсы считается плохой практикой.
я хочу понимать, что же именно возвращает функция.

2020-11-16 16:12 UTC, merged